/** Pure, advisory eligibility only. Never authorizes a venue order by itself.
 * A durable provider must atomically reserve the mandate+approval+clientOrderId
 * and the execution adapter must revalidate after restart/reconciliation.
 */
export type MandateState = 'active' | 'paused' | 'revoked' | 'expired'
export type ApprovalState = 'approved' | 'pending' | 'rejected' | 'consumed' | 'revoked'
export interface ExecutionMandate {
  id: string
  revision: string
  state: MandateState
  accountId: string
  venue: string
  instruments: readonly string[]
  sides: readonly ('buy' | 'sell')[]
  maxOrderQuantity: string
  maxOrderNotional: string
  expiresAt: string
}
export interface IndependentApproval {
  id: string
  mandateId: string
  mandateRevision: string
  state: ApprovalState
  requestedBy: string
  approvedBy: string
  clientOrderId: string
  intentHash: string
  expiresAt: string
}
export interface TrustedExecutionEvidence {
  /** Generated by server-side deterministic risk, never passed through from a browser/model. */
  origin: 'server-risk'
  observedAt: string
  orderNotional: string
  killSwitchEngaged: boolean
  reconciliationHealthy: boolean
  ownershipVerified: boolean
  brokerHealthy: boolean
  reduceOnlyVerified: boolean
  unresolvedIntent: boolean
}
export interface ExecutionEligibilityInput {
  mandate?: ExecutionMandate
  approval?: IndependentApproval
  evidence?: TrustedExecutionEvidence
  accountId: string
  venue: string
  instrument: string
  side: 'buy' | 'sell'
  quantity: string
  reduceOnly: boolean
  requester: string
  clientOrderId: string
  intentHash: string
  now: string
}
export interface ExecutionEligibility {
  /** True means eligible for ATOMIC RESERVATION ONLY; it is not an execution grant. */
  eligibleForReservation: boolean
  blockers: readonly string[]
  mandateId?: string
  approvalId?: string
}

function timestamp(value: string): number | undefined {
  if (!/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:\.\d+)?Z$/.test(value)) return undefined
  const result = Date.parse(value)
  return Number.isFinite(result) ? result : undefined
}
/** Reject scientific notation, negative values, ambiguity and unconstrained input length. */
export function canonicalPositiveDecimal(value: string): string | undefined {
  if (value.length > 100 || !/^(?:0|[1-9]\d*)(?:\.\d+)?$/.test(value)) return undefined
  const [integer, fraction = ''] = value.split('.')
  const cleanFraction = fraction.replace(/0+$/, '')
  if (integer === '0' && cleanFraction === '') return undefined
  return cleanFraction ? `${integer}.${cleanFraction}` : integer
}
export function decimalWithin(value: string, maximum: string): boolean {
  const a = canonicalPositiveDecimal(value), b = canonicalPositiveDecimal(maximum)
  if (a === undefined || b === undefined) return false
  const [ai, af = ''] = a.split('.'), [bi, bf = ''] = b.split('.')
  if (ai.length !== bi.length) return ai.length < bi.length
  if (ai !== bi) return ai < bi
  return af.padEnd(Math.max(af.length, bf.length), '0') <= bf.padEnd(Math.max(af.length, bf.length), '0')
}

export function evaluateExecutionEligibility(input: ExecutionEligibilityInput): ExecutionEligibility {
  const blockers: string[] = []
  const now = timestamp(input.now)
  if (now === undefined) blockers.push('invalid_clock')
  if (!input.clientOrderId.trim() || !input.intentHash.trim() || !input.requester.trim()) blockers.push('missing_identity')
  const mandate = input.mandate
  if (!mandate) blockers.push('mandate_missing')
  else {
    if (mandate.state !== 'active') blockers.push('mandate_inactive')
    if (!mandate.id.trim() || !mandate.revision.trim()) blockers.push('mandate_identity_missing')
    if (mandate.accountId !== input.accountId || mandate.venue !== input.venue || !mandate.instruments.includes(input.instrument) || !mandate.sides.includes(input.side)) blockers.push('mandate_scope_mismatch')
    if (!decimalWithin(input.quantity, mandate.maxOrderQuantity)) blockers.push('quantity_exceeds_mandate')
    const end = timestamp(mandate.expiresAt)
    if (now === undefined || end === undefined || end <= now) blockers.push('mandate_expired_or_invalid')
  }
  const evidence = input.evidence
  if (!evidence || evidence.origin !== 'server-risk') blockers.push('trusted_risk_missing')
  else {
    const observed = timestamp(evidence.observedAt)
    if (now === undefined || observed === undefined || observed > now + 1000 || now - observed > 5000) blockers.push('risk_evidence_stale')
    if (evidence.killSwitchEngaged || !evidence.reconciliationHealthy || !evidence.ownershipVerified || !evidence.brokerHealthy || evidence.unresolvedIntent) blockers.push('execution_safety_blocked')
    if (input.reduceOnly && !evidence.reduceOnlyVerified) blockers.push('reduce_only_unverified')
    if (!mandate || !decimalWithin(evidence.orderNotional, mandate.maxOrderNotional)) blockers.push('notional_exceeds_mandate')
  }
  const approval = input.approval
  if (!approval) blockers.push('independent_approval_missing')
  else {
    if (approval.state !== 'approved') blockers.push('independent_approval_inactive')
    if (!approval.id.trim() || !approval.approvedBy.trim() || approval.approvedBy === input.requester || approval.requestedBy !== input.requester) blockers.push('approval_not_independent')
    if (!mandate || approval.mandateId !== mandate.id || approval.mandateRevision !== mandate.revision || approval.clientOrderId !== input.clientOrderId || approval.intentHash !== input.intentHash) blockers.push('approval_binding_mismatch')
    const end = timestamp(approval.expiresAt)
    if (now === undefined || end === undefined || end <= now) blockers.push('approval_expired_or_invalid')
  }
  return { eligibleForReservation: blockers.length === 0, blockers, ...(mandate ? { mandateId: mandate.id } : {}), ...(approval ? { approvalId: approval.id } : {}) }
}
