"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-07-12 13:00:25.447865
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_sources_status'), ['status'], unique=False)

    op.create_table('defi_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_name', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=True),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=38, scale=18), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'chain', 'metric_type', name='uq_defi_metric_entity')
    )
    with op.batch_alter_table('defi_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defi_metrics_chain'), ['chain'], unique=False)
        batch_op.create_index(batch_op.f('ix_defi_metrics_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defi_metrics_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_defi_metrics_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_defi_metrics_metric_type'), ['metric_type'], unique=False)

    op.create_table('fintwit_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('account_weight', sa.Float(), nullable=False),
    sa.Column('historical_accuracy', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('provider_user_id', sa.String(), nullable=True),
    sa.Column('collection_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'username', name='uq_fintwit_platform_username')
    )
    with op.batch_alter_table('fintwit_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fintwit_accounts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_fintwit_accounts_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_fintwit_accounts_username'), ['username'], unique=False)

    op.create_table('market_quotes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('base_asset', sa.String(), nullable=False),
    sa.Column('quote_asset', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('change_24h_pct', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('volume_24h_base', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('volume_24h_quote', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('high_24h', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('low_24h', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('bid', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('ask', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'symbol', 'source_timestamp', name='uq_market_quote_source_time')
    )
    with op.batch_alter_table('market_quotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_quotes_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_quotes_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_quotes_source_timestamp'), ['source_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_quotes_symbol'), ['symbol'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('related_symbols', sa.JSON(), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_news_content_hash'),
    sa.UniqueConstraint('source', 'external_id', name='uq_news_source_external')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_source'), ['source'], unique=False)

    op.create_table('onchain_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('metric_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provenance_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'chain', 'entity_id', 'metric_type', name='uq_onchain_metric_entity')
    )
    with op.batch_alter_table('onchain_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onchain_metrics_chain'), ['chain'], unique=False)
        batch_op.create_index(batch_op.f('ix_onchain_metrics_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_onchain_metrics_provider'), ['provider'], unique=False)

    op.create_table('shared_market_intelligence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('market_regime', sa.String(), nullable=False),
    sa.Column('summary_markdown', sa.Text(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('source_snapshot_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('catalyst', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_asset'), ['asset'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('external_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('source_license', sa.String(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('retention_policy', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_key', name='uq_source_provider_external')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_provider_type'), ['provider_type'], unique=False)

    op.create_table('stripe_webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload_hash', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stripe_webhook_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stripe_webhook_events_stripe_event_id'), ['stripe_event_id'], unique=True)

    op.create_table('subscription_plans',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('monthly_price', sa.Float(), nullable=True),
    sa.Column('monthly_credits', sa.Integer(), nullable=False),
    sa.Column('max_daily_reports', sa.Integer(), nullable=False),
    sa.Column('max_alerts', sa.Integer(), nullable=False),
    sa.Column('allowed_data_sources', sa.JSON(), nullable=False),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('plan', sa.String(), nullable=False),
    sa.Column('credit_balance', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('google_user_id', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_user_id'), ['google_user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_stripe_customer_id'), ['stripe_customer_id'], unique=False)

    op.create_table('agent_conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_conversations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_user_id'), ['user_id'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('credits_spent', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_user_id'), ['user_id'], unique=False)

    op.create_table('billing_checkout_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('public_reference', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('checkout_mode', sa.String(), nullable=False),
    sa.Column('stripe_payment_link_url', sa.Text(), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_reference', name='uq_billing_checkout_public_reference')
    )
    with op.batch_alter_table('billing_checkout_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_checkout_intents_public_reference'), ['public_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_billing_checkout_intents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_checkout_intents_stripe_checkout_session_id'), ['stripe_checkout_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_checkout_intents_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_checkout_intents_user_id'), ['user_id'], unique=False)

    op.create_table('credit_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('credits_delta', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('data_source_sync_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'idempotency_key', name='uq_provider_sync_idempotency')
    )
    with op.batch_alter_table('data_source_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_sync_runs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_source_sync_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_source_sync_runs_trace_id'), ['trace_id'], unique=False)

    op.create_table('llm_call_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('prompt_summary', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_call_logs_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_call_logs_user_id'), ['user_id'], unique=False)

    op.create_table('market_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume_24h', sa.Float(), nullable=False),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('funding_rate', sa.Float(), nullable=True),
    sa.Column('open_interest', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_snapshots_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('notification_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_notification_idempotency')
    )
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_deliveries_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_locale'), ['locale'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_deliveries_user_id'), ['user_id'], unique=False)

    op.create_table('portfolio_autopilot_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('nav', sa.Float(), nullable=False),
    sa.Column('account_count', sa.Integer(), nullable=False),
    sa.Column('findings_json', sa.JSON(), nullable=False),
    sa.Column('concentration_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_autopilot_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_autopilot_reviews_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_autopilot_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('provider_sync_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('cursor_before', sa.Text(), nullable=True),
    sa.Column('cursor_after', sa.Text(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('rate_limit_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('usage_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'idempotency_key', name='uq_provider_log_idempotency')
    )
    with op.batch_alter_table('provider_sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_sync_logs_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_sync_logs_status'), ['status'], unique=False)

    op.create_table('raw_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('license_status', sa.String(), nullable=False),
    sa.Column('retention_policy', sa.String(), nullable=False),
    sa.Column('processing_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash', name='uq_raw_content_hash'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_raw_provider_external')
    )
    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_fetched_at'), ['fetched_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_documents_source_id'), ['source_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('source_intelligence_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_intelligence_id'], ['shared_market_intelligence.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_language'), ['language'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_price_id', sa.String(), nullable=True),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_stripe_subscription_id'), ['stripe_subscription_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('trading_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('permissions_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_accounts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_accounts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_accounts_venue'), ['venue'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_usage_event_idempotency')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_subject', sa.String(), nullable=False),
    sa.Column('provider_email', sa.String(), nullable=True),
    sa.Column('provider_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_identity_provider_subject')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_identities_provider_email'), ['provider_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)

    op.create_table('user_preferences',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('preferred_assets', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('preferred_style', sa.String(), nullable=False),
    sa.Column('locale', sa.String(), nullable=False),
    sa.Column('excluded_assets', sa.JSON(), nullable=False),
    sa.Column('notification_channels', sa.JSON(), nullable=False),
    sa.Column('subscription_cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('subscription_cancel_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('imessage_recipient', sa.String(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('slack_webhook_url', sa.String(), nullable=True),
    sa.Column('email_recipient', sa.String(), nullable=True),
    sa.Column('portfolio_autopilot_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('account_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('available_margin', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('exposure', sa.Float(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('raw_event_reference', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('agent_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_messages_user_id'), ['user_id'], unique=False)

    op.create_table('exchange_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('adapter', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('credential_reference', sa.String(), nullable=True),
    sa.Column('credential_ciphertext', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_health_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'adapter', name='uq_exchange_connection_account_adapter')
    )
    with op.batch_alter_table('exchange_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchange_connections_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_connections_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchange_connections_user_id'), ['user_id'], unique=False)

    op.create_table('normalized_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('raw_document_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.JSON(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('engagement_metrics', sa.JSON(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('license_status', sa.String(), nullable=False),
    sa.Column('retention_policy', sa.String(), nullable=False),
    sa.Column('redistribution_allowed', sa.Boolean(), nullable=False),
    sa.Column('stable_hash', sa.String(), nullable=False),
    sa.Column('event_fingerprint', sa.String(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('alert_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['raw_document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stable_hash', name='uq_normalized_stable_hash')
    )
    with op.batch_alter_table('normalized_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalized_documents_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_event_fingerprint'), ['event_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_final_score'), ['final_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_raw_document_id'), ['raw_document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_normalized_documents_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_normalized_documents_stable_hash'), ['stable_hash'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategies_user_id'), ['user_id'], unique=False)

    op.create_table('agent_message_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('citation_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['agent_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'citation_index', name='uq_message_citation_index')
    )
    with op.batch_alter_table('agent_message_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_message_sources_message_id'), ['message_id'], unique=False)

    op.create_table('agent_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_message_id', sa.String(), nullable=False),
    sa.Column('assistant_message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_calls_count', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('usage_recorded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['agent_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_message_id'], ['agent_messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_user_id'), ['user_id'], unique=False)

    op.create_table('entity_mentions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('mention_text', sa.String(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['normalized_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'symbol', name='uq_document_entity_symbol')
    )
    with op.batch_alter_table('entity_mentions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_mentions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_mentions_symbol'), ['symbol'], unique=False)

    op.create_table('sentiment_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.String(), nullable=False),
    sa.Column('source_credibility', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('asset_relevance', sa.Float(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('event_fingerprint', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['normalized_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sentiment_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentiment_signals_document_id'), ['document_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sentiment_signals_event_fingerprint'), ['event_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_signals_final_score'), ['final_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_sentiment_signals_sentiment_label'), ['sentiment_label'], unique=False)

    op.create_table('strategy_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('intent_type', sa.String(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('confirmation_required', sa.Boolean(), nullable=False),
    sa.Column('confirmation_token_hash', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_strategy_intent_idempotency')
    )
    with op.batch_alter_table('strategy_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_intents_approval_status'), ['approval_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_intents_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_intents_intent_type'), ['intent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_intents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_intents_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_intents_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_risk_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('max_position', sa.Float(), nullable=False),
    sa.Column('max_notional', sa.Float(), nullable=False),
    sa.Column('max_leverage', sa.Float(), nullable=False),
    sa.Column('max_daily_loss', sa.Float(), nullable=False),
    sa.Column('max_drawdown', sa.Float(), nullable=False),
    sa.Column('max_orders_per_minute', sa.Integer(), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('pause_opening', sa.Boolean(), nullable=False),
    sa.Column('global_kill_switch', sa.Boolean(), nullable=False),
    sa.Column('policy_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'strategy_version', name='uq_strategy_risk_version')
    )
    with op.batch_alter_table('strategy_risk_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_risk_policies_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_risk_policies_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('draft_json', sa.JSON(), nullable=False),
    sa.Column('config_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_version')
    )
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_versions_config_hash'), ['config_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_versions_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_versions_user_id'), ['user_id'], unique=False)

    op.create_table('agent_tool_calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('arguments_json', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_tool_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_tool_calls_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tool_calls_tool_name'), ['tool_name'], unique=False)

    op.create_table('strategy_activations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('intent_id', sa.String(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('runtime_command_id', sa.String(), nullable=True),
    sa.Column('runtime_ack_json', sa.JSON(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intent_id'], ['strategy_intents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('intent_id', name='uq_strategy_activation_intent')
    )
    with op.batch_alter_table('strategy_activations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_activations_runtime_command_id'), ['runtime_command_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_activations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_activations_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_activations_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('activation_id', sa.String(), nullable=True),
    sa.Column('runtime_run_id', sa.String(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performance_json', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['activation_id'], ['strategy_activations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('runtime_run_id', name='uq_strategy_runtime_run')
    )
    with op.batch_alter_table('strategy_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_runs_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_runs_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_runs_user_id'), ['user_id'], unique=False)

    op.create_table('order_intents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('strategy_version', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('venue', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('notional', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('risk_limits_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('confirmation_token_hash', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_event_reference', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_order_intent_idempotency')
    )
    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_intents_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_intents_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_intents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_intents_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_intents_user_id'), ['user_id'], unique=False)

    op.create_table('position_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('mark_price', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('leverage', sa.Float(), nullable=False),
    sa.Column('raw_event_reference', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('position_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_position_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshots_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshots_instrument'), ['instrument'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshots_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_position_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('reconciliation_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('local_state_json', sa.JSON(), nullable=False),
    sa.Column('exchange_state_json', sa.JSON(), nullable=False),
    sa.Column('differences_json', sa.JSON(), nullable=False),
    sa.Column('actions_json', sa.JSON(), nullable=False),
    sa.Column('raw_event_reference', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_records_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_records_user_id'), ['user_id'], unique=False)

    op.create_table('signal_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=False),
    sa.Column('strategy_version', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('source_ids', sa.JSON(), nullable=False),
    sa.Column('source_urls', sa.JSON(), nullable=False),
    sa.Column('data_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fetch_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('freshness', sa.Float(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=False),
    sa.Column('feature_version', sa.String(), nullable=False),
    sa.Column('signal_direction', sa.String(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=False),
    sa.Column('target_position', sa.Float(), nullable=False),
    sa.Column('execution_note', sa.Text(), nullable=True),
    sa.Column('risk_state', sa.String(), nullable=False),
    sa.Column('raw_event_reference', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_strategy_signal_idempotency')
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_events_asset'), ['asset'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_events_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_events_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_events_user_id'), ['user_id'], unique=False)

    op.create_table('trading_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['agent_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_trading_audit_idempotency')
    )
    with op.batch_alter_table('trading_audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_audit_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_audit_logs_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('order_journal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('order_intent_id', sa.String(), nullable=False),
    sa.Column('client_order_id', sa.String(), nullable=False),
    sa.Column('exchange_order_id', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('instrument', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=False),
    sa.Column('remaining_quantity', sa.Float(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('reduce_only', sa.Boolean(), nullable=False),
    sa.Column('event_json', sa.JSON(), nullable=False),
    sa.Column('raw_event_reference', sa.JSON(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['trading_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_intent_id'], ['order_intents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', 'sequence', name='uq_order_journal_sequence'),
    sa.UniqueConstraint('idempotency_key', name='uq_order_journal_idempotency')
    )
    with op.batch_alter_table('order_journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_journal_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_client_order_id'), ['client_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_exchange_order_id'), ['exchange_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_order_intent_id'), ['order_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_journal_user_id'), ['user_id'], unique=False)

    op.create_table('risk_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('strategy_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('order_intent_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('limits_json', sa.JSON(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_intent_id'], ['order_intents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['strategy_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_decisions_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_decisions_order_intent_id'), ['order_intent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_decisions_strategy_id'), ['strategy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_decisions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_decisions_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_decisions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_risk_decisions_order_intent_id'))
        batch_op.drop_index(batch_op.f('ix_risk_decisions_decision'))

    op.drop_table('risk_decisions')
    with op.batch_alter_table('order_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_journal_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_journal_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_order_journal_state'))
        batch_op.drop_index(batch_op.f('ix_order_journal_run_id'))
        batch_op.drop_index(batch_op.f('ix_order_journal_order_intent_id'))
        batch_op.drop_index(batch_op.f('ix_order_journal_exchange_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_journal_created_at'))
        batch_op.drop_index(batch_op.f('ix_order_journal_client_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_journal_account_id'))

    op.drop_table('order_journal')
    with op.batch_alter_table('trading_audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_trading_audit_logs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_trading_audit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_trading_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_trading_audit_logs_action'))

    op.drop_table('trading_audit_logs')
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_signal_events_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_signal_events_run_id'))
        batch_op.drop_index(batch_op.f('ix_signal_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_signal_events_asset'))

    op.drop_table('signal_events')
    with op.batch_alter_table('reconciliation_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_status'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_records_account_id'))

    op.drop_table('reconciliation_records')
    with op.batch_alter_table('position_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_position_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_position_snapshots_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_position_snapshots_instrument'))
        batch_op.drop_index(batch_op.f('ix_position_snapshots_captured_at'))
        batch_op.drop_index(batch_op.f('ix_position_snapshots_account_id'))

    op.drop_table('position_snapshots')
    with op.batch_alter_table('order_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_intents_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_intents_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_order_intents_status'))
        batch_op.drop_index(batch_op.f('ix_order_intents_run_id'))
        batch_op.drop_index(batch_op.f('ix_order_intents_account_id'))

    op.drop_table('order_intents')
    with op.batch_alter_table('strategy_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_runs_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_runs_status'))
        batch_op.drop_index(batch_op.f('ix_strategy_runs_account_id'))

    op.drop_table('strategy_runs')
    with op.batch_alter_table('strategy_activations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_activations_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_activations_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_activations_status'))
        batch_op.drop_index(batch_op.f('ix_strategy_activations_runtime_command_id'))

    op.drop_table('strategy_activations')
    with op.batch_alter_table('agent_tool_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_tool_calls_tool_name'))
        batch_op.drop_index(batch_op.f('ix_agent_tool_calls_run_id'))

    op.drop_table('agent_tool_calls')
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_versions_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_versions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_versions_config_hash'))

    op.drop_table('strategy_versions')
    with op.batch_alter_table('strategy_risk_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_risk_policies_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_risk_policies_strategy_id'))

    op.drop_table('strategy_risk_policies')
    with op.batch_alter_table('strategy_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_intents_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_intents_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_intents_status'))
        batch_op.drop_index(batch_op.f('ix_strategy_intents_intent_type'))
        batch_op.drop_index(batch_op.f('ix_strategy_intents_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_intents_approval_status'))

    op.drop_table('strategy_intents')
    with op.batch_alter_table('sentiment_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentiment_signals_sentiment_label'))
        batch_op.drop_index(batch_op.f('ix_sentiment_signals_final_score'))
        batch_op.drop_index(batch_op.f('ix_sentiment_signals_event_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_sentiment_signals_document_id'))

    op.drop_table('sentiment_signals')
    with op.batch_alter_table('entity_mentions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_mentions_symbol'))
        batch_op.drop_index(batch_op.f('ix_entity_mentions_document_id'))

    op.drop_table('entity_mentions')
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_conversation_id'))

    op.drop_table('agent_runs')
    with op.batch_alter_table('agent_message_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_message_sources_message_id'))

    op.drop_table('agent_message_sources')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_user_id'))
        batch_op.drop_index(batch_op.f('ix_strategies_status'))
        batch_op.drop_index(batch_op.f('ix_strategies_conversation_id'))

    op.drop_table('strategies')
    with op.batch_alter_table('normalized_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalized_documents_stable_hash'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_source_type'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_raw_document_id'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_published_at'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_provider'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_final_score'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_event_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_normalized_documents_author'))

    op.drop_table('normalized_documents')
    with op.batch_alter_table('exchange_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchange_connections_user_id'))
        batch_op.drop_index(batch_op.f('ix_exchange_connections_status'))
        batch_op.drop_index(batch_op.f('ix_exchange_connections_account_id'))

    op.drop_table('exchange_connections')
    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_status'))
        batch_op.drop_index(batch_op.f('ix_agent_messages_conversation_id'))

    op.drop_table('agent_messages')
    with op.batch_alter_table('account_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_snapshots_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_snapshots_captured_at'))
        batch_op.drop_index(batch_op.f('ix_account_snapshots_account_id'))

    op.drop_table('account_snapshots')
    op.drop_table('user_preferences')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_identities_provider_email'))
        batch_op.drop_index(batch_op.f('ix_user_identities_provider'))

    op.drop_table('user_identities')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_usage_events_created_at'))

    op.drop_table('usage_events')
    with op.batch_alter_table('trading_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_accounts_venue'))
        batch_op.drop_index(batch_op.f('ix_trading_accounts_user_id'))
        batch_op.drop_index(batch_op.f('ix_trading_accounts_status'))

    op.drop_table('trading_accounts')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_stripe_customer_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_user_id'))
        batch_op.drop_index(batch_op.f('ix_reports_language'))

    op.drop_table('reports')
    with op.batch_alter_table('raw_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_published_at'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_provider'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_processing_status'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_raw_documents_content_hash'))

    op.drop_table('raw_documents')
    with op.batch_alter_table('provider_sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_sync_logs_status'))
        batch_op.drop_index(batch_op.f('ix_provider_sync_logs_provider_id'))

    op.drop_table('provider_sync_logs')
    with op.batch_alter_table('portfolio_autopilot_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_autopilot_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_autopilot_reviews_status'))

    op.drop_table('portfolio_autopilot_reviews')
    with op.batch_alter_table('notification_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_locale'))
        batch_op.drop_index(batch_op.f('ix_notification_deliveries_channel'))

    op.drop_table('notification_deliveries')
    with op.batch_alter_table('market_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_snapshots_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_snapshots_asset_id'))

    op.drop_table('market_snapshots')
    with op.batch_alter_table('llm_call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_task_type'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_status'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_provider'))
        batch_op.drop_index(batch_op.f('ix_llm_call_logs_locale'))

    op.drop_table('llm_call_logs')
    with op.batch_alter_table('data_source_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_sync_runs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_data_source_sync_runs_status'))
        batch_op.drop_index(batch_op.f('ix_data_source_sync_runs_provider_id'))

    op.drop_table('data_source_sync_runs')
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_ledger_user_id'))

    op.drop_table('credit_ledger')
    with op.batch_alter_table('billing_checkout_intents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_checkout_intents_user_id'))
        batch_op.drop_index(batch_op.f('ix_billing_checkout_intents_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_billing_checkout_intents_stripe_checkout_session_id'))
        batch_op.drop_index(batch_op.f('ix_billing_checkout_intents_status'))
        batch_op.drop_index(batch_op.f('ix_billing_checkout_intents_public_reference'))

    op.drop_table('billing_checkout_intents')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_user_id'))

    op.drop_table('backtest_runs')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_user_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('agent_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_agent_conversations_status'))

    op.drop_table('agent_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_stripe_customer_id'))
        batch_op.drop_index(batch_op.f('ix_users_google_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('subscription_plans')
    with op.batch_alter_table('stripe_webhook_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stripe_webhook_events_stripe_event_id'))

    op.drop_table('stripe_webhook_events')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_provider_type'))
        batch_op.drop_index(batch_op.f('ix_sources_provider'))

    op.drop_table('sources')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_asset'))

    op.drop_table('signals')
    op.drop_table('shared_market_intelligence')
    with op.batch_alter_table('onchain_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onchain_metrics_provider'))
        batch_op.drop_index(batch_op.f('ix_onchain_metrics_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_onchain_metrics_chain'))

    op.drop_table('onchain_metrics')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_source'))
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))
        batch_op.drop_index(batch_op.f('ix_news_items_canonical_url'))

    op.drop_table('news_items')
    with op.batch_alter_table('market_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_quotes_symbol'))
        batch_op.drop_index(batch_op.f('ix_market_quotes_source_timestamp'))
        batch_op.drop_index(batch_op.f('ix_market_quotes_provider'))
        batch_op.drop_index(batch_op.f('ix_market_quotes_fetched_at'))

    op.drop_table('market_quotes')
    with op.batch_alter_table('fintwit_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fintwit_accounts_username'))
        batch_op.drop_index(batch_op.f('ix_fintwit_accounts_platform'))
        batch_op.drop_index(batch_op.f('ix_fintwit_accounts_category'))

    op.drop_table('fintwit_accounts')
    with op.batch_alter_table('defi_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defi_metrics_metric_type'))
        batch_op.drop_index(batch_op.f('ix_defi_metrics_fetched_at'))
        batch_op.drop_index(batch_op.f('ix_defi_metrics_entity_type'))
        batch_op.drop_index(batch_op.f('ix_defi_metrics_entity_id'))
        batch_op.drop_index(batch_op.f('ix_defi_metrics_chain'))

    op.drop_table('defi_metrics')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_status'))
        batch_op.drop_index(batch_op.f('ix_data_sources_category'))

    op.drop_table('data_sources')
    op.drop_table('assets')
    # ### end Alembic commands ###

