import type { PureGammaCapabilityDescriptor } from './contracts.js'

/**
 * Complete target ownership map for PureGamma Harness.
 *
 * Everything is a plugin. `legacyOwners` are extraction/wrapping inputs only;
 * Harness-side packages must never import them as permanent architectural
 * dependencies. Vendor-specific implementations live in provider plugins under
 * the stable services declared here.
 */
export const PUREGAMMA_CAPABILITIES: readonly PureGammaCapabilityDescriptor[] = [
  {
    id: 'auth',
    packageName: '@puregamma/dsh-auth',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgAuth', 'pgEntitlements'],
    tools: [],
    ui: ['settings.account', 'conversation.auth-state'],
    legacyOwners: ['apps/api/routers/auth*', 'apps/web/middleware.ts', 'apps/ios', 'apps/android'],
  },
  {
    id: 'agent-chat',
    packageName: '@puregamma/dsh-agent-chat',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgConversationPolicy', 'pgAgentQuota'],
    tools: [],
    ui: ['conversation.root', 'conversation.citations', 'conversation.tool-calls'],
    legacyOwners: ['apps/api/routers/*agent*', 'packages/agents', 'docs/AGENT_CHAT_ARCHITECTURE.md'],
  },
  {
    id: 'market-data',
    packageName: '@puregamma/dsh-market-data',
    plane: 'host',
    risk: 'read-only',
    services: ['pgMarketData', 'pgNews', 'pgProviderHealth'],
    tools: ['market_snapshot', 'market_news', 'market_provider_health'],
    ui: ['tool.market-snapshot', 'tool.market-news'],
    legacyOwners: ['packages/data', 'apps/api/routers/*market*', 'docs/PUBLIC_DATA_SOURCES.md'],
  },
  {
    id: 'data-sources',
    packageName: '@puregamma/dsh-data-sources',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgDataSources', 'pgSourceEntitlements'],
    tools: ['data_source_status', 'data_source_catalog'],
    ui: ['settings.data-sources', 'resource.data-source-health'],
    legacyOwners: ['packages/data', 'apps/api/routers/admin*', 'apps/web/app/*/admin*'],
  },
  {
    id: 'research',
    packageName: '@puregamma/dsh-research',
    plane: 'dual',
    risk: 'read-only',
    services: ['pgResearch'],
    tools: [
      'research_today',
      'research_overnight',
      'research_portfolio_impact',
      'research_upcoming_events',
      'research_opportunities',
      'research_alerts',
    ],
    ui: ['tool.research-run', 'resource.research-artifact'],
    legacyOwners: ['packages/agents', 'packages/harness', 'apps/web/plugins/builtin/research', 'docs/developer/HARNESS_RESEARCH_ARCHITECTURE.md'],
  },
  {
    id: 'research-runner',
    packageName: '@puregamma/dsh-research-runner',
    plane: 'host',
    risk: 'stateful',
    services: ['pgResearchSandbox'],
    tools: ['research_code_run'],
    ui: [],
    legacyOwners: ['packages/research_runner', 'services/*runner*'],
  },
  {
    id: 'secretary',
    packageName: '@puregamma/dsh-secretary',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgSecretary', 'pgDailyBrief', 'pgVoice'],
    tools: ['secretary_brief', 'secretary_schedule', 'secretary_voice'],
    ui: ['tool.secretary', 'settings.secretary'],
    legacyOwners: ['apps/web/plugins/builtin/secretary', 'packages/agents', 'packages/notifications'],
  },
  {
    id: 'skills',
    packageName: '@puregamma/dsh-skills',
    plane: 'host',
    risk: 'stateful',
    services: ['pgSkills', 'pgWorkflowPolicy'],
    tools: ['skill_catalog', 'skill_run'],
    ui: ['settings.skills'],
    legacyOwners: ['packages/skills', 'docs/SKILLS_LIBRARY.md'],
  },
  {
    id: 'portfolio',
    packageName: '@puregamma/dsh-portfolio',
    plane: 'dual',
    risk: 'read-only',
    services: ['pgPortfolio', 'pgNav'],
    tools: ['portfolio_snapshot', 'portfolio_positions', 'portfolio_nav'],
    ui: ['tool.portfolio', 'resource.portfolio'],
    legacyOwners: ['packages/portfolio', 'apps/web/plugins/builtin/portfolio', 'apps/api/services/portfolio_service.py'],
  },
  {
    id: 'portfolio-autopilot',
    packageName: '@puregamma/dsh-portfolio-autopilot',
    plane: 'host',
    risk: 'stateful',
    services: ['pgPortfolioAutopilot'],
    tools: ['portfolio_review', 'portfolio_review_schedule'],
    ui: ['settings.portfolio-autopilot', 'resource.portfolio-review'],
    legacyOwners: ['packages/portfolio', 'packages/notifications', 'apps/api/services/*portfolio*'],
  },
  {
    id: 'options',
    packageName: '@puregamma/dsh-options',
    plane: 'dual',
    risk: 'read-only',
    services: ['pgOptions'],
    tools: [
      'options_chain',
      'options_long_gamma',
      'options_surface',
      'options_surface_tickers',
      'options_earnings_gamma',
    ],
    ui: ['tool.options-chain', 'tool.options-surface'],
    legacyOwners: ['packages/options', 'apps/web/plugins/builtin/options'],
  },
  {
    id: 'backtest',
    packageName: '@puregamma/dsh-backtest',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgBacktest'],
    tools: [
      'backtest_status',
      'backtest_compile',
      'backtest_run',
      'backtest_runs',
      'backtest_result',
      'backtest_cancel',
      'backtest_export',
      'backtest_save_strategy',
      'backtest_refresh_data',
    ],
    ui: ['tool.backtest', 'resource.backtest-artifact'],
    legacyOwners: ['packages/backtest', 'apps/api/routers/backtest*', 'apps/api/services/*backtest*'],
  },
  {
    id: 'memory',
    packageName: '@puregamma/dsh-memory',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgMemory'],
    tools: ['memory_search', 'memory_propose', 'memory_forget'],
    ui: ['settings.memory'],
    legacyOwners: ['packages/memory', 'docs/developer/MEMORY_ARCHITECTURE.md'],
  },
  {
    id: 'trading',
    packageName: '@puregamma/dsh-trading',
    plane: 'dual',
    risk: 'money-movement',
    services: ['pgExecution', 'pgRisk', 'pgReconciliation', 'pgLedger', 'pgKillSwitch'],
    tools: ['trade_preview', 'trade_submit', 'trade_cancel', 'trading_status'],
    ui: ['tool.trade-preview', 'tool.order', 'resource.trading-status'],
    legacyOwners: ['packages/trading', 'packages/live_trading', 'apps/web/plugins/builtin/trading'],
  },
  {
    id: 'trading-mandates',
    packageName: '@puregamma/dsh-trading-mandates',
    plane: 'dual',
    risk: 'money-movement',
    services: ['pgTradingMandates', 'pgTradingApproval'],
    tools: ['mandate_status', 'mandate_pause', 'mandate_resume'],
    ui: ['settings.trading-mandates', 'resource.trading-safety'],
    legacyOwners: ['packages/trading', 'packages/live_trading', 'docs/developer/AUTOMATED_TRADING_FOUNDATION.md'],
  },
  {
    id: 'nautilus-runtime',
    packageName: '@puregamma/dsh-nautilus-runtime',
    plane: 'host',
    risk: 'money-movement',
    services: ['pgNautilusRuntime'],
    tools: ['nautilus_runtime_status'],
    ui: ['resource.nautilus-runtime'],
    legacyOwners: ['packages/nautilus', 'services/nautilus-runtime'],
  },
  {
    id: 'pg-tsy-runtime',
    packageName: '@puregamma/dsh-pg-tsy-runtime',
    plane: 'host',
    risk: 'money-movement',
    services: ['pgTsyRuntime'],
    tools: ['quant_runtime_status'],
    ui: ['resource.quant-runtime'],
    legacyOwners: ['vendor/pg-tsy-core-bootstrap'],
  },
  {
    id: 'notifications',
    packageName: '@puregamma/dsh-notifications',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgNotifications'],
    tools: ['notification_send', 'notification_channels'],
    ui: ['settings.notifications'],
    legacyOwners: ['packages/notifications', 'apps/api/routers/*notification*'],
  },
  {
    id: 'billing',
    packageName: '@puregamma/dsh-billing',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgBilling', 'pgEntitlements', 'pgCredits', 'pgGatewayWallet'],
    tools: ['billing_status', 'usage_status', 'wallet_status'],
    ui: ['settings.billing', 'resource.usage', 'resource.wallet'],
    legacyOwners: ['packages/billing', 'apps/api/routers/*billing*'],
  },
  {
    id: 'api-gateway',
    packageName: '@puregamma/dsh-api-gateway',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgModelGateway', 'pgModelCatalog', 'pgUsageMeter'],
    tools: ['gateway_usage', 'gateway_keys', 'gateway_models'],
    ui: ['settings.api-gateway', 'resource.gateway-usage'],
    legacyOwners: ['packages/gateway', 'docs/AI_API_GATEWAY.md'],
  },
  {
    id: 'mobile-api',
    packageName: '@puregamma/dsh-mobile-api',
    plane: 'host',
    risk: 'stateful',
    services: ['pgMobileCapabilities', 'pgDeepLinks', 'pgPushRouting'],
    tools: [],
    ui: [],
    legacyOwners: ['apps/ios', 'apps/android', 'docs/mobile/MOBILE_API_CONTRACT.md'],
  },
  {
    id: 'admin',
    packageName: '@puregamma/dsh-admin',
    plane: 'dual',
    risk: 'stateful',
    services: ['pgAdmin', 'pgPluginInventory'],
    tools: ['admin_health', 'admin_plugin_inventory'],
    ui: ['settings.admin', 'resource.admin-health'],
    legacyOwners: ['apps/web/app/*/admin*', 'apps/api/routers/admin*'],
  },
] as const

export function capabilityById(id: PureGammaCapabilityDescriptor['id']) {
  return PUREGAMMA_CAPABILITIES.find(capability => capability.id === id)
}
