"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, CirclePause, CirclePlay, FlaskConical, Loader2, OctagonX, RefreshCw, ShieldCheck, Square } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { Badge, DataSourceStatusBadge, StatCell, StatusDot } from "@/components/puregamma";
import type { Locale } from "@/i18n/routing";
import { withLocale } from "@/i18n/routing";
import { confirmStrategyActivation, controlStrategy, createRuntimeStrategy, getNautilusStrategies, getRuntimeStrategy, getTradingAccounts, getTradingOrders, getTradingPerformance, getTradingPositions, getTradingRuntimeEvents, getTradingRuntimeHealth, getTradingRuntimeMarket, previewStrategyActivation, runNautilusBacktest, syncTradingRuntime, type RuntimeEvent, type RuntimeMarketQuote, type RuntimeStrategy, type TradingAccount, type TradingOrder, type TradingPerformance, type TradingPosition, type TradingRuntimeHealth } from "@/lib/api";

type View = "overview" | "strategies" | "detail" | "paper" | "runtime" | "positions" | "risk";

export function StrategyRuntimeConsole({ locale, view = "overview", strategyId }: { locale: Locale; view?: View; strategyId?: string }) {
  const zh = locale === "zh";
  const [strategies, setStrategies] = useState<RuntimeStrategy[]>([]);
  const [selected, setSelected] = useState<RuntimeStrategy | null>(null);
  const [accounts, setAccounts] = useState<TradingAccount[]>([]);
  const [positions, setPositions] = useState<TradingPosition[]>([]);
  const [orders, setOrders] = useState<TradingOrder[]>([]);
  const [performance, setPerformance] = useState<TradingPerformance[]>([]);
  const [health, setHealth] = useState<TradingRuntimeHealth | null>(null);
  const [marketQuotes, setMarketQuotes] = useState<RuntimeMarketQuote[]>([]);
  const [runtimeEvents, setRuntimeEvents] = useState<RuntimeEvent[]>([]);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [preview, setPreview] = useState<{ id: string; confirmation: string; mode: string } | null>(null);
  const [confirmation, setConfirmation] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const [draftName, setDraftName] = useState("BTC 1h momentum");
  const [draftAsset, setDraftAsset] = useState("BTC");

  const load = useCallback(async () => {
    const results = await Promise.allSettled([getNautilusStrategies(locale), getTradingAccounts(), getTradingPositions(), getTradingOrders(), getTradingRuntimeHealth(), getTradingRuntimeMarket(), getTradingRuntimeEvents(), strategyId ? getRuntimeStrategy(strategyId) : Promise.resolve(null), getTradingPerformance()]);
    if (results[0].status === "fulfilled") setStrategies(results[0].value.strategies);
    if (results[1].status === "fulfilled") setAccounts(results[1].value.accounts);
    if (results[2].status === "fulfilled") setPositions(results[2].value.positions);
    if (results[3].status === "fulfilled") setOrders(results[3].value.orders);
    if (results[4].status === "fulfilled") setHealth(results[4].value);
    if (results[5].status === "fulfilled") setMarketQuotes(results[5].value.quotes);
    if (results[6].status === "fulfilled") setRuntimeEvents(results[6].value.events);
    if (results[7].status === "fulfilled" && results[7].value) setSelected(results[7].value.strategy);
    if (results[8].status === "fulfilled") setPerformance(results[8].value.accounts);
  }, [locale, strategyId]);

  useEffect(() => { void load(); }, [load]);
  const act = async (key: string, callback: () => Promise<unknown>) => { setBusy(key); setError(""); try { await callback(); await load(); } catch (reason) { setError((reason as Error).message); } finally { setBusy(""); } };

  const create = () => act("create", async () => {
    const result = await createRuntimeStrategy({ name: draftName, description: zh ? "从 Runtime Console 创建的策略草稿" : "Strategy draft created from Runtime Console", instruments: [`${draftAsset}USDT`], venues: ["MOCK"], timeframe: "1h", strategy_type: "trend", entry_rules: [{ type: "momentum", condition: "close_above_20_period_high" }], exit_rules: [{ type: "risk", condition: "stop_or_take_profit" }], sentiment_sources: ["rss", "fintwit", "x-twitter", "bloomberg"], execution_mode: "PAPER" });
    setSelected(result.strategy); setCreateOpen(false);
  });

  const makePreview = (strategy: RuntimeStrategy, mode: "PAPER" | "SHADOW") => act(`preview-${strategy.id}`, async () => {
    const result = await previewStrategyActivation(strategy.id, mode, accounts[0]?.id);
    setPreview({ id: result.intent.id, confirmation: result.intent.confirmation, mode }); setConfirmation(""); setSelected(strategy);
  });
  const confirm = () => selected && preview ? act("confirm", async () => { await confirmStrategyActivation(selected.id, preview.id, confirmation); setPreview(null); setConfirmation(""); }) : undefined;
  const refreshMarket = () => act("market-refresh", async () => { const result = await getTradingRuntimeMarket(true); setMarketQuotes(result.quotes); });
  const syncAccount = () => accounts[0] ? act("account-sync", () => syncTradingRuntime(accounts[0].id)) : undefined;

  const nav = [{ href: "/nautilus", label: zh ? "总览" : "Overview" }, { href: "/strategies", label: zh ? "策略" : "Strategies" }, { href: "/trading/paper", label: "Paper" }, { href: "/trading/runtime", label: "Runtime" }, { href: "/trading/positions", label: zh ? "仓位" : "Positions" }, { href: "/trading/risk", label: zh ? "风险" : "Risk" }];
  const activeStrategy = selected || (strategyId ? strategies.find((item) => item.id === strategyId) : null);

  return <div className="space-y-5">
    <div className="border-b border-border-pg pb-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-text-pg-muted">Nautilus Runtime</p><h1 className="mt-2 text-3xl font-semibold md:text-4xl">{zh ? "策略运行控制台" : "Strategy Runtime Console"}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-text-pg-muted">{zh ? "Agent 负责研究和控制意图；独立 Runtime 负责事件、风险、订单状态与模拟执行。" : "The Agent owns research and control intent; the isolated runtime owns events, risk, order state, and simulated execution."}</p></div><Badge tone="neutral"><StatusDot tone="amber" />LIVE DISABLED</Badge></div><div className="mt-5 flex gap-2 overflow-x-auto">{nav.map((item) => <Link key={item.href} href={withLocale(locale, item.href)} className="whitespace-nowrap border border-border-pg px-3 py-2 text-sm hover:border-border-pg-strong rounded-lg">{item.label}</Link>)}</div></div>
    {error ? <div className="border border-status-negative p-3 text-sm text-status-negative rounded-lg">{error}</div> : null}
    <section className="grid gap-px border border-border-pg bg-border-pg sm:grid-cols-2 xl:grid-cols-4 rounded-xl overflow-hidden">
      <Metric label="Runtime" value={String(health?.status || "UNAVAILABLE")} />
      <Metric label={zh ? "执行适配器" : "Adapter"} value={health?.adapter.adapter || "-"} />
      <Metric label="Nautilus core" value={health?.nautilus.available ? `NATIVE ${health.nautilus.version || ""}` : "MOCK BRIDGE"} />
      <Metric label={zh ? "运行数量" : "Runs"} value={String(health?.runs ?? 0)} />
    </section>
    {(view === "overview" || view === "runtime") && health?.adapters?.length ? <section className="grid gap-px border border-border-pg bg-border-pg sm:grid-cols-3 rounded-xl overflow-hidden">{health.adapters.map((adapter) => <div key={adapter.adapter} className="flex items-center justify-between gap-3 bg-bg-panel px-4 py-3"><div><p className="text-sm font-medium capitalize">{adapter.adapter.replace("_", " ")}</p><p className="mt-1 text-xs text-text-pg-dim">{adapter.live ? "LIVE" : "NON-LIVE"}</p></div><DataSourceStatusBadge status={adapter.status} locale={locale} /></div>)}</section> : null}
    {(view === "overview" || view === "runtime") ? <section><div className="mb-3 flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{zh ? "Paper 行情源" : "Paper market feed"}</h2><Command title={zh ? "刷新" : "Refresh"} icon={RefreshCw} busy={busy === "market-refresh"} onClick={refreshMarket} /></div><div className="grid gap-px border border-border-pg bg-border-pg sm:grid-cols-2 xl:grid-cols-4 rounded-xl overflow-hidden">{marketQuotes.map((quote) => <div key={quote.asset} className="bg-bg-panel p-4"><div className="flex items-center justify-between gap-3"><p className="font-semibold">{quote.asset}</p><DataSourceStatusBadge status={quote.stale ? "DEGRADED" : "HEALTHY"} locale={locale} /></div><p className="mt-3 text-xl font-semibold">${quote.price.toLocaleString(locale, { maximumFractionDigits: quote.price >= 1000 ? 2 : 4 })}</p><p className="mt-2 text-xs text-text-pg-dim">{quote.provider.replace("_public", "")} · {new Date(quote.timestamp).toLocaleTimeString(locale)}</p></div>)}{!marketQuotes.length ? <div className="bg-bg-panel p-4 text-sm text-text-pg-muted">{zh ? "尚未同步公开行情。" : "Public quotes have not synced yet."}</div> : null}</div></section> : null}
    <section className="border border-status-warning bg-bg-panel-muted p-4 rounded-xl"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 text-status-warning" /><div><h2 className="font-semibold">{zh ? "执行边界" : "Execution boundary"}</h2><p className="mt-1 text-sm text-text-pg-muted">PAPER / SHADOW / Mock Exchange only. Live orders, withdrawals, transfers, and wallet signing are unavailable.</p></div></div></section>

    {(view === "overview" || view === "strategies") ? <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">{zh ? "策略版本" : "Strategy versions"}</h2><button onClick={() => setCreateOpen(!createOpen)} className="border border-border-pg px-3 py-2 text-sm hover:border-border-pg-strong rounded-lg">{zh ? "新建草稿" : "New draft"}</button></div>{createOpen ? <div className="mb-4 grid gap-3 border border-border-pg bg-bg-panel p-4 sm:grid-cols-[1fr_140px_auto] rounded-xl"><input value={draftName} onChange={(event) => setDraftName(event.target.value)} aria-label={zh ? "策略名称" : "Strategy name"} className="border border-border-pg bg-bg-panel-muted px-3 py-2 text-sm rounded-lg" /><select value={draftAsset} onChange={(event) => setDraftAsset(event.target.value)} aria-label={zh ? "资产" : "Asset"} className="border border-border-pg bg-bg-panel-muted px-3 py-2 text-sm rounded-lg">{["BTC", "ETH", "SOL", "HYPE"].map((item) => <option key={item}>{item}</option>)}</select><button onClick={create} disabled={busy === "create"} className="border border-border-pg-strong bg-pg-white px-4 py-2 text-sm font-semibold text-pg-black disabled:opacity-40 rounded-lg">{busy === "create" ? <Loader2 className="h-4 w-4 animate-spin" /> : (zh ? "创建" : "Create")}</button></div> : null}<div className="grid gap-4 xl:grid-cols-2">{strategies.map((strategy) => <StrategyCard key={strategy.id} strategy={strategy} locale={locale} busy={busy} onPreview={makePreview} onBacktest={(item) => act(`backtest-${item.id}`, () => runNautilusBacktest(item.id, "mock"))} />)}{!strategies.length ? <div className="border border-border-pg p-5 text-sm text-text-pg-muted rounded-xl">{zh ? "暂无策略。可通过 Agent 对话或此页面创建草稿。" : "No strategies yet. Create a draft here or through Agent chat."}</div> : null}</div></section> : null}

    {(view === "detail" && activeStrategy) ? <StrategyDetail strategy={activeStrategy} locale={locale} busy={busy} onPreview={makePreview} onControl={(action) => act(action, () => controlStrategy(activeStrategy.id, action))} /> : null}
    {(view === "paper" || view === "runtime") ? <RuntimeRuns strategies={strategies} locale={locale} busy={busy} onControl={(strategy, action) => act(`${strategy.id}-${action}`, () => controlStrategy(strategy.id, action))} /> : null}
    {view === "runtime" ? <RuntimeEvents events={runtimeEvents} locale={locale} /> : null}
    {view === "positions" ? <PositionTable positions={positions} performance={performance[0]} locale={locale} busy={busy === "account-sync"} onSync={syncAccount} /> : null}
    {view === "risk" ? <RiskView strategies={strategies} orders={orders} locale={locale} /> : null}

    {preview ? <section className="border border-status-warning bg-bg-panel p-4 rounded-xl"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 h-5 w-5 text-status-warning" /><div className="min-w-0 flex-1"><h2 className="font-semibold">{preview.mode} {zh ? "激活确认" : "activation confirmation"}</h2><p className="mt-2 text-sm text-text-pg-muted">{zh ? "Runtime 尚未启动。请逐字输入下面的完整确认短语。" : "The runtime has not started. Enter the complete phrase exactly."}</p><code className="mt-3 block overflow-x-auto border border-border-pg bg-bg-panel-muted p-3 text-xs rounded-xl">{preview.confirmation}</code><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} aria-label={zh ? "确认短语" : "Confirmation phrase"} className="mt-3 w-full border border-border-pg bg-bg-panel-muted px-3 py-2 text-sm rounded-lg" placeholder={zh ? "手动输入完整确认短语" : "Type the complete confirmation phrase"} /><button onClick={confirm} disabled={!confirmation || busy === "confirm"} className="mt-3 border border-status-warning px-4 py-2 text-sm font-semibold text-status-warning disabled:opacity-40 rounded-lg">{busy === "confirm" ? <Loader2 className="h-4 w-4 animate-spin" /> : (zh ? "确认并启动" : "Confirm and start")}</button></div></div></section> : null}
  </div>;
}

const Metric = StatCell;
function StrategyCard({ strategy, locale, busy, onPreview, onBacktest }: { strategy: RuntimeStrategy; locale: Locale; busy: string; onPreview: (strategy: RuntimeStrategy, mode: "PAPER" | "SHADOW") => void; onBacktest: (strategy: RuntimeStrategy) => void }) { const zh = locale === "zh"; return <article className="border border-border-pg bg-bg-panel rounded-lg"><div className="flex items-start justify-between gap-3 border-b border-border-pg p-4"><div><Link href={withLocale(locale, `/strategies/${strategy.id}`)} className="font-semibold hover:underline">{strategy.name}</Link><p className="mt-1 text-xs text-text-pg-muted">v{strategy.current_version} · {strategy.draft.timeframe} · {strategy.draft.instruments.join(", ")}</p></div><DataSourceStatusBadge status={strategy.status} locale={locale} /></div><div className="grid grid-cols-3 gap-px bg-border-pg"><Metric label={zh ? "模式" : "Mode"} value={strategy.execution_mode} /><Metric label={zh ? "杠杆" : "Leverage"} value={`${strategy.draft.leverage}x`} /><Metric label={zh ? "名义上限" : "Max notional"} value={`$${strategy.draft.max_notional}`} /></div><div className="flex flex-wrap gap-2 border-t border-border-pg p-3"><Command title={zh ? "回测" : "Backtest"} icon={FlaskConical} busy={busy === `backtest-${strategy.id}`} onClick={() => onBacktest(strategy)} /><Command title="Paper" icon={CirclePlay} busy={busy === `preview-${strategy.id}`} onClick={() => onPreview(strategy, "PAPER")} /><Command title="Shadow" icon={ShieldCheck} busy={busy === `preview-${strategy.id}`} onClick={() => onPreview(strategy, "SHADOW")} /></div></article>; }
function Command({ title, icon: Icon, busy, onClick }: { title: string; icon: LucideIcon; busy: boolean; onClick: () => void }) { return <button onClick={onClick} disabled={busy} className="inline-flex items-center gap-2 border border-border-pg px-3 py-2 text-xs hover:border-border-pg-strong disabled:opacity-40 rounded-lg">{busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Icon className="h-3.5 w-3.5" />}{title}</button>; }
function StrategyDetail({ strategy, locale, busy, onPreview, onControl }: { strategy: RuntimeStrategy; locale: Locale; busy: string; onPreview: (strategy: RuntimeStrategy, mode: "PAPER" | "SHADOW") => void; onControl: (action: "pause" | "resume" | "stop") => void }) { const zh = locale === "zh"; return <section className="space-y-4"><div className="border border-border-pg bg-bg-panel p-5 rounded-xl"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-semibold">{strategy.name}</h2><p className="mt-2 text-sm text-text-pg-muted">{strategy.description}</p></div><DataSourceStatusBadge status={strategy.status} locale={locale} /></div><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label={zh ? "版本" : "Version"} value={`v${strategy.current_version}`} /><Metric label={zh ? "标的" : "Instruments"} value={strategy.draft.instruments.join(", ")} /><Metric label={zh ? "数据源" : "Sources"} value={strategy.draft.sentiment_sources.join(", ") || "market"} /><Metric label={zh ? "最大回撤" : "Max drawdown"} value={`${strategy.draft.max_drawdown * 100}%`} /></dl></div><div className="flex flex-wrap gap-2"><Command title="Paper" icon={CirclePlay} busy={busy.startsWith("preview")} onClick={() => onPreview(strategy, "PAPER")} /><Command title={zh ? "暂停" : "Pause"} icon={CirclePause} busy={busy === "pause"} onClick={() => onControl("pause")} /><Command title={zh ? "恢复" : "Resume"} icon={RefreshCw} busy={busy === "resume"} onClick={() => onControl("resume")} /><Command title={zh ? "停止" : "Stop"} icon={Square} busy={busy === "stop"} onClick={() => onControl("stop")} /></div></section>; }
function RuntimeRuns({ strategies, locale, busy, onControl }: { strategies: RuntimeStrategy[]; locale: Locale; busy: string; onControl: (strategy: RuntimeStrategy, action: "pause" | "resume" | "stop") => void }) { const zh = locale === "zh"; return <section><h2 className="mb-3 text-lg font-semibold">{zh ? "运行状态" : "Runtime runs"}</h2><div className="overflow-x-auto border border-border-pg rounded-xl"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border-pg text-left text-xs text-text-pg-muted">{[zh ? "策略" : "Strategy", zh ? "模式" : "Mode", zh ? "状态" : "Status", zh ? "开始时间" : "Started", zh ? "控制" : "Controls"].map((item) => <th key={item} className="p-3 font-medium">{item}</th>)}</tr></thead><tbody>{strategies.filter((item) => item.latest_run).map((strategy) => <tr key={strategy.id} className="border-b border-border-pg last:border-0"><td className="p-3 font-medium">{strategy.name}</td><td className="p-3">{strategy.latest_run?.execution_mode}</td><td className="p-3"><DataSourceStatusBadge status={strategy.latest_run?.status || "-"} locale={locale} /></td><td className="p-3 text-text-pg-muted">{strategy.latest_run?.started_at ? new Date(strategy.latest_run.started_at).toLocaleString(locale) : "-"}</td><td className="flex gap-2 p-3"><Command title={zh ? "暂停" : "Pause"} icon={CirclePause} busy={busy.includes(strategy.id)} onClick={() => onControl(strategy, "pause")} /><Command title={zh ? "停止" : "Stop"} icon={Square} busy={busy.includes(strategy.id)} onClick={() => onControl(strategy, "stop")} /></td></tr>)}</tbody></table></div></section>; }
function PositionTable({ positions, performance, locale, busy, onSync }: { positions: TradingPosition[]; performance?: TradingPerformance; locale: Locale; busy: boolean; onSync: () => void }) { const zh = locale === "zh"; const money = (value = 0) => `$${value.toLocaleString(locale, { maximumFractionDigits: 2 })}`; return <section className="space-y-4"><div className="flex items-center justify-between gap-3"><h2 className="text-lg font-semibold">{zh ? "模拟仓位" : "Paper positions"}</h2><Command title={zh ? "同步账本" : "Sync ledger"} icon={RefreshCw} busy={busy} onClick={onSync} /></div><div className="grid gap-px border border-border-pg bg-border-pg sm:grid-cols-2 xl:grid-cols-4 rounded-xl overflow-hidden"><Metric label={zh ? "账户权益" : "Equity"} value={money(performance?.equity)} /><Metric label={zh ? "当日盈亏" : "Daily PnL"} value={money(performance?.daily_pnl)} /><Metric label={zh ? "总敞口" : "Exposure"} value={money(performance?.exposure)} /><Metric label={zh ? "可用保证金" : "Available margin"} value={money(performance?.available_margin)} /></div><div className="overflow-x-auto border border-border-pg rounded-xl"><table className="w-full min-w-[720px] text-sm"><thead><tr className="border-b border-border-pg text-left text-xs text-text-pg-muted">{[zh ? "标的" : "Instrument", zh ? "方向" : "Side", zh ? "数量" : "Quantity", zh ? "均价" : "Average", zh ? "标记价" : "Mark", "PnL", zh ? "模式" : "Mode"].map((item) => <th key={item} className="p-3 font-medium">{item}</th>)}</tr></thead><tbody>{positions.map((position) => <tr key={position.id} className="border-b border-border-pg"><td className="p-3 font-semibold">{position.instrument}</td><td className="p-3">{position.side}</td><td className="p-3">{position.quantity}</td><td className="p-3">{position.average_price}</td><td className="p-3">{position.mark_price}</td><td className={position.unrealized_pnl >= 0 ? "p-3 text-status-positive" : "p-3 text-status-negative"}>{position.unrealized_pnl.toFixed(2)}</td><td className="p-3">PAPER</td></tr>)}</tbody></table>{!positions.length ? <p className="p-4 text-sm text-text-pg-muted">{zh ? "暂无模拟仓位。" : "No paper positions."}</p> : null}</div></section>; }
function RuntimeEvents({ events, locale }: { events: RuntimeEvent[]; locale: Locale }) { const zh = locale === "zh"; return <section><h2 className="mb-3 text-lg font-semibold">{zh ? "运行事件" : "Runtime events"}</h2><div className="border border-border-pg bg-bg-panel rounded-lg">{events.slice(0, 20).map((event) => <div key={event.id} className="grid gap-1 border-b border-border-pg p-3 last:border-0 sm:grid-cols-[180px_1fr_auto]"><p className="text-xs font-semibold">{event.event_type}</p><p className="truncate text-xs text-text-pg-muted">{String(event.payload.asset || event.aggregate_id)} {String(event.payload.direction || "")}</p><time className="text-xs text-text-pg-dim">{new Date(event.created_at).toLocaleString(locale)}</time></div>)}{!events.length ? <p className="p-4 text-sm text-text-pg-muted">{zh ? "暂无运行事件。" : "No runtime events."}</p> : null}</div></section>; }
function RiskView({ strategies, orders, locale }: { strategies: RuntimeStrategy[]; orders: TradingOrder[]; locale: Locale }) { const zh = locale === "zh"; const rejected = orders.filter((item) => ["REJECTED", "UNKNOWN", "RECONCILIATION_REQUIRED"].includes(item.state)); return <section className="grid gap-4 xl:grid-cols-2"><div className="border border-border-pg bg-bg-panel p-4 rounded-xl"><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4" />{zh ? "策略风险额度" : "Strategy risk limits"}</h2><div className="mt-4 space-y-3">{strategies.map((strategy) => <div key={strategy.id} className="border-l-2 border-border-pg-strong pl-3 text-sm"><p className="font-medium">{strategy.name}</p><p className="mt-1 text-text-pg-muted">Max ${strategy.draft.max_notional} · {strategy.draft.leverage}x · DD {strategy.draft.max_drawdown * 100}%</p></div>)}</div></div><div className="border border-border-pg bg-bg-panel p-4 rounded-xl"><h2 className="flex items-center gap-2 font-semibold"><OctagonX className="h-4 w-4 text-status-negative" />{zh ? "拒绝与不确定订单" : "Rejected and uncertain orders"}</h2><div className="mt-4 space-y-3">{rejected.map((order) => <div key={order.id} className="text-sm"><p>{order.instrument} · {order.state}</p><p className="text-xs text-text-pg-muted">{order.client_order_id}</p></div>)}{!rejected.length ? <p className="text-sm text-text-pg-muted">{zh ? "当前无拒绝记录。" : "No current rejection records."}</p> : null}</div></div></section>; }
