from __future__ import annotations

from enum import Enum


class ExecutionMode(str, Enum):
    BACKTEST = "BACKTEST"
    PAPER = "PAPER"
    SHADOW = "SHADOW"
    LIVE = "LIVE"


class IntentType(str, Enum):
    CREATE_STRATEGY = "CREATE_STRATEGY"
    MODIFY_STRATEGY = "MODIFY_STRATEGY"
    BACKTEST_STRATEGY = "BACKTEST_STRATEGY"
    START_PAPER_STRATEGY = "START_PAPER_STRATEGY"
    START_SHADOW_STRATEGY = "START_SHADOW_STRATEGY"
    REQUEST_LIVE_ACTIVATION = "REQUEST_LIVE_ACTIVATION"
    PAUSE_STRATEGY = "PAUSE_STRATEGY"
    RESUME_STRATEGY = "RESUME_STRATEGY"
    STOP_STRATEGY = "STOP_STRATEGY"
    VIEW_STRATEGY_STATUS = "VIEW_STRATEGY_STATUS"
    VIEW_STRATEGY_PERFORMANCE = "VIEW_STRATEGY_PERFORMANCE"
    VIEW_POSITION = "VIEW_POSITION"
    VIEW_OPEN_ORDERS = "VIEW_OPEN_ORDERS"
    RECONCILE_ACCOUNT = "RECONCILE_ACCOUNT"
    MANUAL_ORDER = "MANUAL_ORDER"
    CANCEL_ORDER = "CANCEL_ORDER"
    CLOSE_POSITION = "CLOSE_POSITION"


class RunState(str, Enum):
    PENDING = "PENDING"
    STARTING = "STARTING"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    STOPPING = "STOPPING"
    STOPPED = "STOPPED"
    ERROR = "ERROR"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"


class OrderState(str, Enum):
    CREATED = "CREATED"
    PREPARED = "PREPARED"
    SUBMITTING = "SUBMITTING"
    SUBMITTED = "SUBMITTED"
    ACCEPTED = "ACCEPTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCEL_PENDING = "CANCEL_PENDING"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    UNKNOWN = "UNKNOWN"
    RECONCILIATION_REQUIRED = "RECONCILIATION_REQUIRED"
